import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { EditorContent, useEditor } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Underline from '@tiptap/extension-underline';
import Heading from '@tiptap/extension-heading';
import './styles.css';

const API_ROOT = (import.meta.env.VITE_API_URL || '').replace(/\/$/, '');
const API = `${API_ROOT}/api`;
const token = () => localStorage.getItem('token') || '';
async function request(path: string, options: RequestInit = {}) { const response = await fetch(API + path, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token()}`, ...options.headers } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Something went wrong'); return data; }
function Shell({ children }: { children: React.ReactNode }) { const navigate = useNavigate(); const user = JSON.parse(localStorage.getItem('user') || 'null'); return <div className="app-shell"><header><button className="brand" onClick={() => navigate('/documents')}>papertrail<span>•</span></button>{user && <div className="user-menu"><span>{user.name}</span><button className="ghost" onClick={() => { localStorage.clear(); navigate('/login'); }}>Log out</button></div>}</header>{children}</div>; }
function Login() { const navigate = useNavigate(); const [email, setEmail] = useState('alice@example.com'); const [error, setError] = useState(''); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { const data = await request('/auth/login', { method: 'POST', body: JSON.stringify({ email }) }); localStorage.setItem('token', data.token); localStorage.setItem('user', JSON.stringify(data.user)); navigate('/documents'); } catch (e) { setError((e as Error).message); } }; return <main className="login-page"><section className="login-copy"><p className="eyebrow">A quiet place for shared work</p><h1>Make room for the thought.</h1><p>Write, shape, and share documents without losing the thread.</p></section><form className="login-card" onSubmit={submit}><div className="mark">pt</div><h2>Welcome back</h2><p className="muted">Choose a seeded account to continue.</p><label>Email address<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" /></label>{error && <div className="error">{error}</div>}<button className="primary" type="submit">Continue <span>→</span></button><small>Alice: alice@example.com<br />Bob: bob@example.com</small></form></main>; }
type Doc = { id: number; title: string; access: 'owned' | 'shared'; ownerName?: string };
function Documents() { const navigate = useNavigate(); const [docs, setDocs] = useState<{ owned: Doc[]; shared: Doc[] }>({ owned: [], shared: [] }); const [error, setError] = useState(''); const load = () => request('/documents').then(setDocs).catch((e) => setError(e.message)); useEffect(() => { void load(); }, []); const create = async () => { const data = await request('/documents', { method: 'POST', body: '{}' }); navigate(`/documents/${data.id}`); }; const importFile = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const form = new FormData(); form.append('file', file); const response = await fetch(`${API}/documents/import`, { method: 'POST', headers: { Authorization: `Bearer ${token()}` }, body: form }); const data = await response.json(); if (!response.ok) setError(data.error); else navigate(`/documents/${data.id}`); }; const list = (items: Doc[], label: string, shared = false) => <section className="doc-section"><div className="section-heading"><h2>{label}</h2><span>{items.length}</span></div>{items.length ? items.map((doc) => <button className="doc-row" key={doc.id} onClick={() => navigate(`/documents/${doc.id}`)}><span className="doc-icon">{shared ? '↗' : '▤'}</span><span><strong>{doc.title}</strong><small>{shared ? `Shared by ${doc.ownerName}` : 'Owned by you'}</small></span><span className="arrow">→</span></button>) : <div className="empty">Nothing here yet.</div>}</section>; return <Shell><main className="dashboard"><div className="dashboard-head"><div><p className="eyebrow">Your workspace</p><h1>Documents</h1></div><div className="actions"><label className="secondary">Import file<input type="file" accept=".txt,.md" onChange={importFile} /></label><button className="primary" onClick={create}>New document <span>+</span></button></div></div>{error && <div className="error">{error}</div>}<div className="document-grid">{list(docs.owned, 'My documents')}{list(docs.shared, 'Shared with me', true)}</div></main></Shell>; }
function Toolbar({ editor }: { editor: any }) { const buttons = [['bold','B','Bold'],['italic','I','Italic'],['underline','U','Underline'],['bulletList','•','Bullet list'],['orderedList','1.','Numbered list']]; const toggle = (command: string) => editor.chain().focus()[command === 'bulletList' ? 'toggleBulletList' : command === 'orderedList' ? 'toggleOrderedList' : `toggle${command[0].toUpperCase()}${command.slice(1)}`]().run(); const runOnMouseDown = (event: React.MouseEvent, command: () => void) => { event.preventDefault(); command(); }; return <div className="toolbar"><button aria-label="Heading 1" onMouseDown={(event) => runOnMouseDown(event, () => editor.chain().focus().toggleHeading({ level: 1 }).run())}>H1</button><button aria-label="Heading 2" onMouseDown={(event) => runOnMouseDown(event, () => editor.chain().focus().toggleHeading({ level: 2 }).run())}>H2</button>{buttons.map(([command, text, label]) => <button aria-label={label} key={command} className={editor.isActive(command) ? 'active' : ''} onMouseDown={(event) => runOnMouseDown(event, () => toggle(command))}>{text}</button>)}</div>; }
function EditorPage() { const { id } = useParams(); const navigate = useNavigate(); const [doc, setDoc] = useState<any>(); const [title, setTitle] = useState(''); const [status, setStatus] = useState(''); const [shareEmail, setShareEmail] = useState(''); const [message, setMessage] = useState(''); const editor = useEditor({ extensions: [StarterKit, Underline, Heading.configure({ levels: [1, 2] })], content: doc?.content, onUpdate: () => setStatus('Unsaved changes') }, [doc]); useEffect(() => { request(`/documents/${id}`).then((data) => { setDoc(data); setTitle(data.title); }).catch((e) => setMessage(e.message)); }, [id]); useEffect(() => { if (editor && doc) editor.commands.setContent(doc.content); }, [editor, doc]); if (!editor || !doc) return <Shell><div className="loading">Loading document…</div></Shell>; const save = async () => { setStatus('Saving…'); try { await request(`/documents/${id}`, { method: 'PUT', body: JSON.stringify({ title, content: editor.getJSON() }) }); setStatus('Saved just now'); } catch (e) { setStatus((e as Error).message); } }; const share = async (event: React.FormEvent) => { event.preventDefault(); try { await request(`/documents/${id}/share`, { method: 'POST', body: JSON.stringify({ email: shareEmail }) }); setMessage(`Shared with ${shareEmail}`); setShareEmail(''); } catch (e) { setMessage((e as Error).message); } }; return <Shell><main className="editor-page"><div className="editor-top"><button className="back" onClick={() => navigate('/documents')}>← Documents</button><div className="save-state">{status || 'All changes saved'}</div><button className="primary save" onClick={save}>Save</button></div><div className="editor-layout"><section className="paper"><input className="title-input" value={title} onChange={(e) => { setTitle(e.target.value); setStatus('Unsaved changes'); }} /><Toolbar editor={editor} /><EditorContent editor={editor} /></section><aside className="side-panel"><div><p className="eyebrow">Document</p><h2>Share this work</h2><p className="muted">Invite a seeded teammate by email. Shared users can edit.</p><form onSubmit={share}><input placeholder="bob@example.com" value={shareEmail} onChange={(e) => setShareEmail(e.target.value)} /><button className="secondary" type="submit">Share</button></form>{message && <p className="notice">{message}</p>}</div><div className="tip"><strong>Access</strong><p>{doc.isOwner ? 'You own this document.' : `Shared by ${doc.owner_name}.`}</p></div></aside></div></main></Shell>; }
function App() { return <Routes><Route path="/login" element={<Login />} /><Route path="/documents" element={<Documents />} /><Route path="/documents/:id" element={<EditorPage />} /><Route path="*" element={<Navigate to={localStorage.getItem('token') ? '/documents' : '/login'} />} /></Routes>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App /></BrowserRouter></React.StrictMode>);